name: MNcustomenchants
version: '1.0-SNAPSHOT'
main: pl.mn.mncustomenchants.main
api-version: '1.20'
commands:
  CustomEnchant:
    usage: /glow
    description: Adds custom Enchants
    permission: MMCustomEnchantments.enchant
