name: MNcustomenchants
version: '1.0-SNAPSHOT'
main: pl.mn.mncustomenchants.main
api-version: '1.20'
commands:
  CustomEnchant:
    usage: /CustomEnchant [enchant] [level]
    description: Adds custom Enchants
    permission: MMCustomEnchantments.enchant
  EditItemV2:
    usage: /EditItemV2 [Edit]
    description: Adds custom Stats
    permission: MMCustomEnchantments.enchant